name: Release to Maven Central

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up Java 11
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish parent, core, and executors to Maven Central
        run: |
          mvn --batch-mode clean deploy \
            -DskipTests \
            -Dgpg.skip=false \
            -Dcentral.skipPublishing=false \
            -pl jpostman-annotations,jpostman-vault,jpostman-github,jpostman-kubernetes,jpostman-vault,jpostman-codegen,jpostman-api-schema

          # To publish all modules instead:
          mvn --batch-mode clean deploy \
            -DskipTests \
            -Dgpg.skip=false \
            -Dcentral.skipPublishing=false \
            -pl .,jpostman-core,jpostman-httpclient,jpostman-restassured,jpostman-playwright,jpostman-unirest,jpostman-secure,jpostman-testng,jpostman-junit
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
