package io.jpostman.annotations.runtime;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.testng.Assert.assertEquals;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.Test;

import io.jpostman.annotations.JPostman;
import io.jpostman.annotations.JPostmanOutputs;

/**
 * Covers the report output generated by the supported diagnostic and fail
 * combinations declared through {@link JPostman.ReportContext}.
 */
class JPostmanReportOutputCombinationsTest {

	private static final String REQUEST = "PREPARED REQUEST";
	private static final String RESPONSE = "RECEIVED RESPONSE";
	private static final String ERROR = "REPORT ERROR";
	private static final String SHORT_LINE = "assertsVerify:  statusCode=201, duration=";
	private static final String FAILED_SHORT_LINE = "assertsVerify:  duration=";

	private static String normalize(String value) {
		return value.replace("\r\n", "\n").replaceAll("(?<=\\.java:)\\d+", "<line>")
				.replaceAll("Duration: \\d{2}:\\d{2}:\\d{2}\\.\\d{3}", "Duration: <duration>");
	}

	@Test
	void diagnosticShortPrintsOnlyCompactExecutionOutput() {
		JPostmanReport report = report(DiagnosticShort.class);
		report.passed(info());

		String output = summary(report);

		assertReportBefore(output, "JPostman Diagnostics:");
		assertContains(output, SHORT_LINE, "(assertsVerify -> newProduct)");
		assertNotContains(output, REQUEST, RESPONSE, "JPostmanInfo {", "FAILED:");
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 1, Failures: 0, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman Diagnostics:\n\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)"),
				output);
	}

	@Test
	void diagnosticExtendPrintsCompactExecutionAndPreparedRequest() {
		JPostmanReport report = report(DiagnosticExtend.class);
		report.passed(info());

		String output = summary(report);

		assertReportBefore(output, "JPostman Diagnostics:");
		assertContains(output, SHORT_LINE, REQUEST);
		assertNotContains(output, RESPONSE, "JPostmanInfo {", "FAILED:");
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 1, Failures: 0, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman Diagnostics:\n\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nPREPARED REQUEST"), output);
	}

	@Test
	void localDebugErrorPrintsErrorRequestAndResponseAfterDiagnostics() {
		JPostmanReport report = report(DiagnosticShort.class);
		JPostmanInfo info = info().debug("error");
		report.failed(info, failure());

		String output = summary(report);

		assertContains(output, "JPostman Diagnostics:", "JPostman Errors:", "java.lang.AssertionError: " + ERROR,
				REQUEST, RESPONSE);
		assertNotContains(output, "JPostman failures", "FAILED:", "JPostmanInfo {");
		assertOrder(output, "JPostman Diagnostics:", FAILED_SHORT_LINE, "JPostman Errors:",
				"java.lang.AssertionError: " + ERROR, REQUEST, RESPONSE);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman Diagnostics:\n\n"
				+ "assertsVerify:  duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nJPostman Errors:\n\njava.lang.AssertionError: REPORT ERROR\n"
				+ "\tat io.jpostman.annotations.runtime.JPostmanReportOutputCombinationsTest$ErrorOrigin.assertsVerify(ErrorOrigin.java)\n"
				+ "\tat io.jpostman.annotations.runtime.JPostmanReportOutputCombinationsTest$ErrorOrigin.assertsVerify(JPostmanReportOutputCombinationsTest.java:<line>)\n"
				+ "\nPREPARED REQUEST\n\nRECEIVED RESPONSE"), output);
	}

	@Test
	void failSkipAllSkipsRemainingExecutionsWithoutAddingFailureDetails() {
		JPostmanReport report = report(FailSkipAll.class);
		report.failed(info(), failure());

		String output = summary(report);

		assertTrue(report.skipRemaining(), output);
		assertContains(output, "JPostman report", "Failures: 1");
		assertNotContains(output, "JPostman failures", SHORT_LINE, REQUEST, RESPONSE, "JPostmanInfo {", "FAILED:");
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "==============================================="), output);
	}

	@Test
	void failErrorIsRejected() {
		IllegalArgumentException error = assertThrows(IllegalArgumentException.class, () -> report(FailError.class));
		assertContains(error.getMessage(), "Allowed values: ignore, skipAll, terminate, request, response, info, all.");
	}

	@Test
	void failRequestPrintsCompactExecutionAndRequest() {
		String output = failedSummary(FailRequest.class);

		assertFailureSection(output);
		assertContains(output, SHORT_LINE, REQUEST);
		assertNotContains(output, RESPONSE, "JPostmanInfo {", "FAILED:", ERROR);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman failures\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nPREPARED REQUEST"), output);
	}

	@Test
	void failInfoPrintsCompactExecutionAndRuntimeInfo() {
		String output = failedSummary(FailInfo.class);

		assertFailureSection(output);
		assertContains(output, SHORT_LINE, "JPostmanInfo {", "annotation=@JPostmanResponse",
				"request=Add a new product");
		assertNotContains(output, REQUEST, RESPONSE, "FAILED:", ERROR);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman failures\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nJPostmanInfo {\n  annotation=@JPostmanResponse\n  method=assertsVerify\n"
				+ "  namespace=product, folder=Product, request=Add a new product\n}"), output);
	}

	@Test
	void failAllPrintsInfoRequestAndResponseWithoutError() {
		String output = failedSummary(FailAll.class);

		assertFailureSection(output);
		assertContains(output, SHORT_LINE, "JPostmanInfo {", REQUEST, RESPONSE);
		assertNotContains(output, "FAILED:", ERROR);
		assertOrder(output, "JPostmanInfo {", REQUEST, RESPONSE);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman failures\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nJPostmanInfo {\n  annotation=@JPostmanResponse\n  method=assertsVerify\n"
				+ "  namespace=product, folder=Product, request=Add a new product\n}\n\n"
				+ "PREPARED REQUEST\n\nRECEIVED RESPONSE"), output);
	}

	@Test
	void failInfoAndRequestPrintsOnlySelectedDetails() {
		String output = failedSummary(FailInfoRequest.class);

		assertFailureSection(output);
		assertContains(output, SHORT_LINE, "JPostmanInfo {", REQUEST);
		assertNotContains(output, RESPONSE, "FAILED:", ERROR);
		assertOrder(output, "JPostmanInfo {", REQUEST);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman failures\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nJPostmanInfo {\n  annotation=@JPostmanResponse\n  method=assertsVerify\n"
				+ "  namespace=product, folder=Product, request=Add a new product\n}\n\nPREPARED REQUEST"), output);
	}

	@Test
	void failErrorAndRequestIsRejected() {
		IllegalArgumentException error = assertThrows(IllegalArgumentException.class,
				() -> report(FailErrorRequest.class));
		assertContains(error.getMessage(), "Allowed values: ignore, skipAll, terminate, request, response, info, all.");
	}

	@Test
	void failRequestAndResponsePrintsOnlyRequestAndResponse() {
		String output = failedSummary(FailRequestResponse.class);

		assertFailureSection(output);
		assertContains(output, SHORT_LINE, REQUEST, RESPONSE);
		assertNotContains(output, "JPostmanInfo {", "FAILED:", ERROR);
		assertOrder(output, REQUEST, RESPONSE);
		assertEquals(normalize("===============================================\nJPostman report\n"
				+ "Total tests run: 1, Passes: 0, Failures: 1, Skips: 0, Duration: <duration>\n"
				+ "===============================================\n\nJPostman failures\n"
				+ "assertsVerify:  statusCode=201, duration=00:00.000, {namespace = product, folder = Product, request = Add a new product} (assertsVerify -> newProduct)\n"
				+ "\nPREPARED REQUEST\n\nRECEIVED RESPONSE"), output);
	}

	private String failedSummary(Class<?> fixture) {
		JPostmanReport report = report(fixture);
		report.failed(info(), failure());
		return summary(report);
	}

	private JPostmanReport report(Class<?> fixture) {
		try {
			Field field = fixture.getDeclaredField("report");
			JPostman.ReportContext configuration = field.getAnnotation(JPostman.ReportContext.class);
			if (configuration == null) {
				throw new AssertionError("Missing @JPostman.ReportContext on " + fixture.getName());
			}
			return new JPostmanReport().configure(configuration.diagnostic(), configuration.fail());
		} catch (ReflectiveOperationException error) {
			throw new AssertionError("Unable to read report fixture " + fixture.getName(), error);
		}
	}

	private JPostmanInfo info() {
		JPostmanInfo info = new JPostmanInfo(new String[0], "", "assertsVerify", "product", "Product",
				"Add a new product");
		info.annotation = "@JPostmanResponse";
		info.method("assertsVerify");
		info.appendMethod("newProduct");
		info.statusCode(201);
		info.requestLog(REQUEST);
		info.responseLog(RESPONSE);
		return info;
	}

	private AssertionError failure() {
		try {
			new ErrorOrigin().assertsVerify();
			throw new AssertionError("Expected fixture failure");
		} catch (AssertionError error) {
			return error;
		}
	}

	private String summary(JPostmanReport report) {
		List<String> output = new ArrayList<>();
		try (JPostmanOutputs.Scope ignored = JPostmanOutputs.use(output::add)) {
			report.summary();
		}
		return normalize(String.join("", output));
	}

	private void assertFailureSection(String output) {
		assertReportBefore(output, "JPostman failures");
	}

	private void assertReportBefore(String output, String section) {
		assertContains(output, "JPostman report", section);
		assertTrue(output.indexOf("JPostman report") < output.indexOf(section), output);
	}

	private void assertContains(String output, String... expected) {
		for (String value : expected) {
			assertTrue(output.contains(value), "Expected to find \"" + value + "\" in:\n" + output);
		}
	}

	private void assertNotContains(String output, String... unexpected) {
		for (String value : unexpected) {
			assertFalse(output.contains(value), "Did not expect to find \"" + value + "\" in:\n" + output);
		}
	}

	private void assertOrder(String output, String... values) {
		int previous = -1;
		for (String value : values) {
			int index = output.indexOf(value, previous + 1);
			assertTrue(index > previous,
					"Expected to find \"" + value + "\" after index " + previous + " in:\n" + output);
			previous = index;
		}
	}

	private static final class ErrorOrigin {
		void assertsVerify() {
			throw new AssertionError(ERROR);
		}
	}

	private static final class DiagnosticShort {
		@JPostman.ReportContext(diagnostic = "short")
		private JPostman.Report report;
	}

	private static final class DiagnosticExtend {
		@JPostman.ReportContext(diagnostic = "extend")
		private JPostman.Report report;
	}

	private static final class FailSkipAll {
		@JPostman.ReportContext(fail = "skipAll")
		private JPostman.Report report;
	}

	private static final class FailError {
		@JPostman.ReportContext(fail = "error")
		private JPostman.Report report;
	}

	private static final class FailRequest {
		@JPostman.ReportContext(fail = "request")
		private JPostman.Report report;
	}

	private static final class FailInfo {
		@JPostman.ReportContext(fail = "info")
		private JPostman.Report report;
	}

	private static final class FailAll {
		@JPostman.ReportContext(fail = "all")
		private JPostman.Report report;
	}

	private static final class FailInfoRequest {
		@JPostman.ReportContext(fail = { "info", "request" })
		private JPostman.Report report;
	}

	private static final class FailErrorRequest {
		@JPostman.ReportContext(fail = { "error", "request" })
		private JPostman.Report report;
	}

	private static final class FailRequestResponse {
		@JPostman.ReportContext(fail = { "request", "response" })
		private JPostman.Report report;
	}
}
